name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0  # https://knowledge.udacity.com/questions/956455
  - python=3.10.9
  - pandas
  - mlflow==2.0.1  # 2.8.1
  - pandas-profiling
  - pip
  - pip:
      - wandb==0.16.0