name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.9 # 3.10.0
  - pandas
  - numpy
  - pytest
  - scipy
  - mlflow==2.0.1  # 2.8.1
  - pip
  - pip:
      - wandb==0.16.0
