name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.9 # 3.10.0
  - mlflow==2.0.1  # 2.8.1
  - hydra-core
  - matplotlib
  - pandas
  - scikit-learn
  - pip
  - pip:
      - wandb==0.16.0
